import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:scrollable_positioned_list/scrollable_positioned_list.dart';

import '../bloc/book.dart';
import '../bloc/chapter.dart';
import '../bloc/verse.dart';
import '../collections/bible.dart';
import '../collections/cache.dart';
import '../bloc/bookname.dart';
import '../bloc/font.dart';
import '../bloc/italic.dart';
import '../bloc/scroll.dart';
import '../bloc/selectorcount.dart';
import '../bloc/size.dart';
import '../bloc/version.dart';
import '../collections/booklist.dart';
import '../constants.dart';
import '../database.dart';
import '../fonts/list.dart';
import '../globals.dart';
import '../langs/books.dart';
import '../translate/page.dart';
import '../versions/bottom.dart';

part 'drawer.dart';

part 'chapter.dart';

part 'selector.dart';

part 'bottom.dart';

part 'compare.dart';

//-------------------------------------------
// Main Page
//-------------------------------------------

class MainPage extends StatefulWidget {
  const MainPage({super.key});

  @override
  State<MainPage> createState() => MainPageState();
}

class MainPageState extends State<MainPage> {
  late String bibleVersion;
  late int bookNumber;

  // Initialize to 0 to show loading state initially
  int totalChapters = 0;

  final scaffoldKey = GlobalKey<ScaffoldState>();

  // This controller must be persistent to ensure smooth scrolling
  late PageController pageController;

  //-------------------------------------------
  // Initialize state: set global language, start data fetch and add listener to refresh notifier.
  //-------------------------------------------
  @override
  void initState() {
    super.initState();

    final version = context.read<VersionBloc>().state;
    Globals.bibleVersion = version;

    final lang = Constants.bibleVersions[version]?['lang'] ?? 'en';
    Globals.bibleVersionLanguage = lang;
    debugPrint("Global language set to: ${Globals.bibleVersionLanguage}");

    fetchMainPage();
    Globals.refreshNotifier.addListener(onReturnSuccess);
  }

  //-------------------------------------------
  // Dispose resources: dispose page controller and remove listener.
  //-------------------------------------------
  @override
  void dispose() {
    pageController.dispose();
    Globals.refreshNotifier.removeListener(onReturnSuccess);
    super.dispose();
  }

  //-------------------------------------------
  // Load caches and determine chapter count, initialize page controller and update state.
  //-------------------------------------------
  Future<void> fetchMainPage() async {
    await loadCacheMarkings();

    if (!mounted) return;
    final version = context.read<VersionBloc>().state;
    final bookNum = context.read<BookNumberBloc>().state;
    final initialPage = context.read<ChapterBloc>().state;

    // Perform async work (count chapters) before calling setState
    final chapters = await getChapterCountForBook(version, bookNum);

    // Initialize pageController (dispose previous if needed)
    pageController = PageController(initialPage: initialPage);

    // Update state synchronously
    if (mounted) {
      setState(() {
        bibleVersion = version;
        bookNumber = bookNum;
        totalChapters = chapters;
      });
    }
  }

  //-------------------------------------------
  // Return number of distinct chapters for a given book and version using Isar query.
  //-------------------------------------------
  Future<int> getChapterCountForBook(
    String bibleVersion,
    int bookNumber,
  ) async {
    // Use Isar's distinct/aggregation API to count unique chapter values
    final count = await isar.bibles
        .filter()
        .versionEqualTo(bibleVersion)
        .bookEqualTo(bookNumber)
        .distinctByChapter() // generated by Isar for the `chapter` field
        .count();

    return count;
  }

  //-------------------------------------------
  // Callback triggered when returning to page: refresh main page data.
  //-------------------------------------------
  void onReturnSuccess() async {
    fetchMainPage();
  }

  //-------------------------------------------
  // Return book abbreviation by book number using BibleBooks helper.
  //-------------------------------------------
  String getbookAbbr(int n) {
    return BibleBooks.getBookAbbrByNumber(n);
  }

  //-------------------------------------------
  // Load cache entries from Isar and populate global bookmark/highlight lists.
  //-------------------------------------------
  Future<void> loadCacheMarkings() async {
    final cacheList = await isar.caches.where().findAll();

    Globals.bookMarkList.clear();
    Globals.highLightList.clear();

    if (cacheList.isNotEmpty) {
      for (final cache in cacheList) {
        if (cache.code == 1) {
          Globals.bookMarkList.add(cache.id);
        } else if (cache.code == 2) {
          Globals.highLightList.add(cache.id);
        }
      }
    }
  }

  //-------------------------------------------
  // Build UI: Scaffold with AppBar, drawer, PageView of chapters and actions.
  //-------------------------------------------
  @override
  Widget build(BuildContext context) {
    return PopScope(
      canPop: false,
      child: Scaffold(
        key: scaffoldKey,
        drawer: const MainDrawer(),
        appBar: AppBar(
          iconTheme: IconThemeData(
            color: Theme.of(context).colorScheme.inversePrimary,
          ),
          backgroundColor: Colors.transparent,
          centerTitle: true,
          flexibleSpace: Container(
            decoration: BoxDecoration(
              gradient: LinearGradient(
                colors: [
                  Theme.of(context).colorScheme.primary,
                  Theme.of(context).colorScheme.surface,
                ],
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
              ),
            ),
          ),
          title: FilledButton(
            onPressed: () {
              Route route = MaterialPageRoute(
                builder: (context) => MainSelector(),
              );
              if (context.mounted) {
                Navigator.push(context, route);
              }
            },
            child: BlocBuilder<BookNumberBloc, int>(
              builder: (context, bookNumber) {
                return BlocBuilder<ChapterBloc, int>(
                  builder: (context, chapterState) {
                    return BlocBuilder<VerseBloc, int>(
                      builder: (context, verseState) {
                        return Text(
                          '${getbookAbbr(bookNumber)} ${chapterState + 1}:$verseState',
                        );
                      },
                    );
                  },
                );
              },
            ),
          ),
          actions: [
            const SizedBox(width: 8),
            FilledButton(
              onPressed: () {
                showModalBottomSheet(
                  context: context,
                  isScrollControlled: true,
                  shape: const RoundedRectangleBorder(
                    borderRadius: BorderRadius.vertical(
                      top: Radius.circular(20),
                    ),
                  ),
                  builder: (context) => VersionsBottomSheet(
                    activeVersion: bibleVersion,
                    onVersionReturnSuccess: ({required String bibleVersion}) {
                      setState(() {
                        context.read<VersionBloc>().add(
                          UpdateVersion(bibleVersion: bibleVersion),
                        );
                      });
                      Navigator.pop(context);
                      fetchMainPage();
                    },
                  ),
                );
              },
              child: BlocBuilder<VersionBloc, String>(
                builder: (context, version) {
                  return Text(version.toUpperCase());
                },
              ),
            ),
            const SizedBox(width: 16),
          ],
          leading: IconButton(
            icon: const Icon(Icons.menu),
            onPressed: () {
              Future.delayed(
                Duration(milliseconds: Globals.navigatorDelay),
                () => scaffoldKey.currentState!.openDrawer(),
              );
            },
          ),
        ),
        body: totalChapters == 0
            ? const Center(child: CircularProgressIndicator())
            : ScrollConfiguration(
                behavior: ScrollConfiguration.of(context).copyWith(
                  dragDevices: {
                    PointerDeviceKind.touch,
                    PointerDeviceKind.mouse,
                  },
                ),
                child: PageView.builder(
                  controller: pageController,
                  itemCount: totalChapters,
                  physics:
                      const BouncingScrollPhysics(), //AlwaysScrollableScrollPhysics(),
                  pageSnapping: true,
                  itemBuilder: (BuildContext context, int index) {
                    return Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: ChapterPage(
                        // The key ensures the page refreshes content when book/version changes
                        key: ValueKey('$bibleVersion-$bookNumber-$index'),
                        bibleVersion: bibleVersion,
                        bookNumber: bookNumber,
                        chapterIndex: index + 1,
                      ),
                    );
                  },
                  onPageChanged: (index) {
                    if (context.read<ChapterBloc>().state != index) {
                      context.read<ChapterBloc>().add(
                        UpdateChapter(chapterNumber: index),
                      );

                      context.read<VerseBloc>().add(
                        UpdateVerse(verseNumber: 1),
                      );
                    }
                    Globals.refreshNotifier.refresh();
                  },
                ),
              ),
      ),
    );
  }
}
