// //-------------------------------------------------------------
// // english
// //-------------------------------------------------------------
//
// List<String> engList = [
//   "Genesis",
//   "Exodus",
//   "Leviticus",
//   "Numbers",
//   "Deuteronomy",
//   "Joshua",
//   "Judges",
//   "Ruth",
//   "1 Samuel",
//   "2 Samuel",
//   "1 Kings",
//   "2 Kings",
//   "1 Chronicles",
//   "2 Chronicles",
//   "Ezra",
//   "Nehemiah",
//   "Esther",
//   "Job",
//   "Psalms",
//   "Proverbs",
//   "Ecclesiastes",
//   "Song of Solomon",
//   "Isaiah",
//   "Jeremiah",
//   "Lamentations",
//   "Ezekiel",
//   "Daniel",
//   "Hosea",
//   "Joel",
//   "Amos",
//   "Obadiah",
//   "Jonah",
//   "Micah",
//   "Nahum",
//   "Habakkuk",
//   "Zephaniah",
//   "Haggai",
//   "Zechariah",
//   "Malachi",
//   "Matthew",
//   "Mark",
//   "Luke",
//   "John",
//   "Acts",
//   "Romans",
//   "1 Corinthians",
//   "2 Corinthians",
//   "Galatians",
//   "Ephesians",
//   "Philippians",
//   "Colossians",
//   "1 Thessalonians",
//   "2 Thessalonians",
//   "1 Timothy",
//   "2 Timothy",
//   "Titus",
//   "Philemon",
//   "Hebrews",
//   "James",
//   "1 Peter",
//   "2 Peter",
//   "1 John",
//   "2 John",
//   "3 John",
//   "Jude",
//   "Revelation"
// ];
//
// List<String> engOTList = [
//   "Genesis",
//   "Exodus",
//   "Leviticus",
//   "Numbers",
//   "Deuteronomy",
//   "Joshua",
//   "Judges",
//   "Ruth",
//   "1 Samuel",
//   "2 Samuel",
//   "1 Kings",
//   "2 Kings",
//   "1 Chronicles",
//   "2 Chronicles",
//   "Ezra",
//   "Nehemiah",
//   "Esther",
//   "Job",
//   "Psalms",
//   "Proverbs",
//   "Ecclesiastes",
//   "Song of Solomon",
//   "Isaiah",
//   "Jeremiah",
//   "Lamentations",
//   "Ezekiel",
//   "Daniel",
//   "Hosea",
//   "Joel",
//   "Amos",
//   "Obadiah",
//   "Jonah",
//   "Micah",
//   "Nahum",
//   "Habakkuk",
//   "Zephaniah",
//   "Haggai",
//   "Zechariah",
//   "Malachi",
// ];
//
// List<String> engNTList = [
//   "Matthew",
//   "Mark",
//   "Luke",
//   "John",
//   "Acts",
//   "Romans",
//   "1 Corinthians",
//   "2 Corinthians",
//   "Galatians",
//   "Ephesians",
//   "Philippians",
//   "Colossians",
//   "1 Thessalonians",
//   "2 Thessalonians",
//   "1 Timothy",
//   "2 Timothy",
//   "Titus",
//   "Philemon",
//   "Hebrews",
//   "James",
//   "1 Peter",
//   "2 Peter",
//   "1 John",
//   "2 John",
//   "3 John",
//   "Jude",
//   "Revelation"
// ];
//
// List<String> engAbbreviations = [
//   "Gen",
//   "Exod",
//   "Lev",
//   "Num",
//   "Deut",
//   "Josh",
//   "Judg",
//   "Ruth",
//   "1 Sam",
//   "2 Sam",
//   "1 Kgs",
//   "2 Kgs",
//   "1 Chr",
//   "2 Chr",
//   "Ezra",
//   "Neh",
//   "Esth",
//   "Job",
//   "Ps",
//   "Prov",
//   "Eccl",
//   "Song",
//   "Isa",
//   "Jer",
//   "Lam",
//   "Ezek",
//   "Dan",
//   "Hos",
//   "Joel",
//   "Amos",
//   "Obad",
//   "Jonah",
//   "Mic",
//   "Nah",
//   "Hab",
//   "Zeph",
//   "Hag",
//   "Zech",
//   "Mal",
//   "Matt",
//   "Mark",
//   "Luke",
//   "John",
//   "Acts",
//   "Rom",
//   "1 Cor",
//   "2 Cor",
//   "Gal",
//   "Eph",
//   "Phil",
//   "Col",
//   "1 Thess",
//   "2 Thess",
//   "1 Tim",
//   "2 Tim",
//   "Titus",
//   "Phlm",
//   "Heb",
//   "James",
//   "1 Pet",
//   "2 Pet",
//   "1 John",
//   "2 John",
//   "3 John",
//   "Jude",
//   "Rev"
// ];

// const Map<int, Map<String, String>> ReverseBookMappings = {
//   // Pentateuch
//   1:  {'abbr': 'GEN', 'name': 'Genesis'},
//   2:  {'abbr': 'EXO', 'name': 'Exodus'},
//   3:  {'abbr': 'LEV', 'name': 'Leviticus'},
//   4:  {'abbr': 'NUM', 'name': 'Numbers'},
//   5:  {'abbr': 'DEU', 'name': 'Deuteronomy'},
//
//   // Historical Books
//   6:  {'abbr': 'JOS', 'name': 'Joshua'},
//   7:  {'abbr': 'JDG', 'name': 'Judges'},
//   8:  {'abbr': 'RUT', 'name': 'Ruth'},
//   9:  {'abbr': '1SA', 'name': '1 Samuel'},
//   10: {'abbr': '2SA', 'name': '2 Samuel'},
//   11: {'abbr': '1KI', 'name': '1 Kings'},
//   12: {'abbr': '2KI', 'name': '2 Kings'},
//   13: {'abbr': '1CH', 'name': '1 Chronicles'},
//   14: {'abbr': '2CH', 'name': '2 Chronicles'},
//   15: {'abbr': 'EZR', 'name': 'Ezra'},
//   16: {'abbr': 'NEH', 'name': 'Nehemiah'},
//   17: {'abbr': 'TOB', 'name': 'Tobit'},
//   18: {'abbr': 'JDT', 'name': 'Judith'},
//   19: {'abbr': 'EST', 'name': 'Esther'},
//   20: {'abbr': '1MAC', 'name': '1 Maccabees'},
//   21: {'abbr': '2MAC', 'name': '2 Maccabees'},
//
//   // Wisdom & Poetry
//   22: {'abbr': 'JOB', 'name': 'Job'},
//   23: {'abbr': 'PSA', 'name': 'Psalms'},
//   24: {'abbr': 'PRO', 'name': 'Proverbs'},
//   25: {'abbr': 'ECC', 'name': 'Ecclesiastes'},
//   26: {'abbr': 'SNG', 'name': 'Song of Songs'},
//   27: {'abbr': 'WIS', 'name': 'Wisdom'},
//   28: {'abbr': 'SIR', 'name': 'Sirach (Ecclesiasticus)'},
//
//   // Prophets
//   29: {'abbr': 'ISA', 'name': 'Isaiah'},
//   30: {'abbr': 'JER', 'name': 'Jeremiah'},
//   31: {'abbr': 'LAM', 'name': 'Lamentations'},
//   32: {'abbr': 'BAR', 'name': 'Baruch'},
//   33: {'abbr': 'EZK', 'name': 'Ezekiel'},
//   34: {'abbr': 'DAN', 'name': 'Daniel'},
//   35: {'abbr': 'HOS', 'name': 'Hosea'},
//   36: {'abbr': 'JOL', 'name': 'Joel'},
//   37: {'abbr': 'AMO', 'name': 'Amos'},
//   38: {'abbr': 'OBA', 'name': 'Obadiah'},
//   39: {'abbr': 'JON', 'name': 'Jonah'},
//   40: {'abbr': 'MIC', 'name': 'Micah'},
//   41: {'abbr': 'NAM', 'name': 'Nahum'},
//   42: {'abbr': 'HAB', 'name': 'Habakkuk'},
//   43: {'abbr': 'ZEP', 'name': 'Zephaniah'},
//   44: {'abbr': 'HAG', 'name': 'Haggai'},
//   45: {'abbr': 'ZEC', 'name': 'Zechariah'},
//   46: {'abbr': 'MAL', 'name': 'Malachi'},
//
//   // New Testament
//   47: {'abbr': 'MAT', 'name': 'Matthew'},
//   48: {'abbr': 'MRK', 'name': 'Mark'},
//   49: {'abbr': 'LUK', 'name': 'Luke'},
//   50: {'abbr': 'JHN', 'name': 'John'},
//   51: {'abbr': 'ACT', 'name': 'Acts'},
//   52: {'abbr': 'ROM', 'name': 'Romans'},
//   53: {'abbr': '1CO', 'name': '1 Corinthians'},
//   54: {'abbr': '2CO', 'name': '2 Corinthians'},
//   55: {'abbr': 'GAL', 'name': 'Galatians'},
//   56: {'abbr': 'EPH', 'name': 'Ephesians'},
//   57: {'abbr': 'PHP', 'name': 'Philippians'},
//   58: {'abbr': 'COL', 'name': 'Colossians'},
//   59: {'abbr': '1TH', 'name': '1 Thessalonians'},
//   60: {'abbr': '2TH', 'name': '2 Thessalonians'},
//   61: {'abbr': '1TI', 'name': '1 Timothy'},
//   62: {'abbr': '2TI', 'name': '2 Timothy'},
//   63: {'abbr': 'TIT', 'name': 'Titus'},
//   64: {'abbr': 'PHM', 'name': 'Philemon'},
//   65: {'abbr': 'HEB', 'name': 'Hebrews'},
//   66: {'abbr': 'JAS', 'name': 'James'},
//   67: {'abbr': '1PE', 'name': '1 Peter'},
//   68: {'abbr': '2PE', 'name': '2 Peter'},
//   69: {'abbr': '1JN', 'name': '1 John'},
//   70: {'abbr': '2JN', 'name': '2 John'},
//   71: {'abbr': '3JN', 'name': '3 John'},
//   72: {'abbr': 'JUD', 'name': 'Jude'},
//   73: {'abbr': 'REV', 'name': 'Revelation'},
// };

// Usage example:
// void main() {
//   print(ReverseBookMappings[17]);
//   // Output: {abbr: TOB, name: Tobit}
//
//   print(ReverseBookMappings[27]?['name']);
//   // Output: Wisdom
// }
